import { Activity } from '../src/types';
import { loadData, saveData, getInitialDefaultData } from '../src/lib/storage';
import { validateActivity } from '../src/lib/rules-engine';

console.log('🌱 Đang khởi tạo dữ liệu mẫu cho giải CNHP Thu Đông 2026...');

const baseData = getInitialDefaultData();

// Tạo các bài chạy mẫu trong Tuần 1 (11/10/2026 - 18/10/2026) và Tuần 2 (19/10/2026 - 25/10/2026)
const sampleActivities: Activity[] = [
  // -----------------------------------------------------------
  // TEAM 1: Chiến Binh Rực Lửa
  // user-1: Nguyễn Hoàng Hà (Đội trưởng) - Chạy đều 4 buổi, tổng 28km
  {
    id: 'act-101',
    userId: 'user-1',
    stravaActivityId: '1001',
    title: 'Khởi động tuần 1 quanh Hồ Tây',
    type: 'Run',
    distanceKm: 8.5,
    movingTimeSec: 2805, // 5:30/km
    elapsedTimeSec: 2900,
    averagePaceSeconds: 330,
    elevationGain: 15,
    startDate: '2026-10-12T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-102',
    userId: 'user-1',
    stravaActivityId: '1002',
    title: 'Chạy nhẹ giữa tuần',
    type: 'Run',
    distanceKm: 6.5,
    movingTimeSec: 2145, // 5:30/km
    elapsedTimeSec: 2200,
    averagePaceSeconds: 330,
    elevationGain: 10,
    startDate: '2026-10-14T06:15:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-103',
    userId: 'user-1',
    stravaActivityId: '1003',
    title: 'Tempo chiều thứ sáu',
    type: 'Run',
    distanceKm: 7.0,
    movingTimeSec: 2170, // 5:10/km (310s)
    elapsedTimeSec: 2250,
    averagePaceSeconds: 310,
    elevationGain: 12,
    startDate: '2026-10-16T17:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 7.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-104',
    userId: 'user-1',
    stravaActivityId: '1004',
    title: 'Chạy sáng chủ nhật cùng team',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 1980, // 5:30/km
    elapsedTimeSec: 2050,
    averagePaceSeconds: 330,
    elevationGain: 8,
    startDate: '2026-10-18T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-2: Trần Văn Mạnh (Siêu cày cuốc) - Chạy 5 buổi, tổng 48km -> Sẽ bị trần 40km vào điểm team!
  {
    id: 'act-201',
    userId: 'user-2',
    stravaActivityId: '1005',
    title: 'Thứ 2 cày cuốc 10km',
    type: 'Run',
    distanceKm: 10.0,
    movingTimeSec: 3200, // 5:20/km
    elapsedTimeSec: 3300,
    averagePaceSeconds: 320,
    elevationGain: 20,
    startDate: '2026-10-12T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 10.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-202',
    userId: 'user-2',
    stravaActivityId: '1006',
    title: 'Thứ 3 duy trì 10km',
    type: 'Run',
    distanceKm: 10.0,
    movingTimeSec: 3200,
    elapsedTimeSec: 3300,
    averagePaceSeconds: 320,
    elevationGain: 20,
    startDate: '2026-10-13T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 10.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-203',
    userId: 'user-2',
    stravaActivityId: '1007',
    title: 'Thứ 5 chạy dài 12km',
    type: 'Run',
    distanceKm: 12.0,
    movingTimeSec: 3840,
    elapsedTimeSec: 3950,
    averagePaceSeconds: 320,
    elevationGain: 25,
    startDate: '2026-10-15T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 12.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-204',
    userId: 'user-2',
    stravaActivityId: '1008',
    title: 'Thứ 7 chạy 8km',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2560,
    elapsedTimeSec: 2600,
    averagePaceSeconds: 320,
    elevationGain: 15,
    startDate: '2026-10-17T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-205',
    userId: 'user-2',
    stravaActivityId: '1009',
    title: 'Chủ nhật long run 8km',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2560,
    elapsedTimeSec: 2600,
    averagePaceSeconds: 320,
    elevationGain: 15,
    startDate: '2026-10-18T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-3: Lê Thị Thu (Nữ) - 3 buổi, tổng 18km (Top nữ)
  {
    id: 'act-301',
    userId: 'user-3',
    stravaActivityId: '1010',
    title: 'Chạy sáng công viên',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2280, // 6:20/km
    elapsedTimeSec: 2350,
    averagePaceSeconds: 380,
    elevationGain: 10,
    startDate: '2026-10-13T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-302',
    userId: 'user-3',
    stravaActivityId: '1011',
    title: 'Chạy chiều cùng bạn',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2280,
    elapsedTimeSec: 2350,
    averagePaceSeconds: 380,
    elevationGain: 10,
    startDate: '2026-10-15T17:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-303',
    userId: 'user-3',
    stravaActivityId: '1012',
    title: 'Chạy chủ nhật hoàn thành chỉ tiêu',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2280,
    elapsedTimeSec: 2350,
    averagePaceSeconds: 380,
    elevationGain: 10,
    startDate: '2026-10-18T06:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-4: Phạm Đức Thắng - Chạy 2 buổi (Thiếu 1 buổi -> Phạt 20k)
  {
    id: 'act-401',
    userId: 'user-4',
    stravaActivityId: '1013',
    title: 'Chạy 9km thứ 3',
    type: 'Run',
    distanceKm: 9.0,
    movingTimeSec: 3240, // 6:00/km
    elapsedTimeSec: 3300,
    averagePaceSeconds: 360,
    elevationGain: 15,
    startDate: '2026-10-13T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 9.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-402',
    userId: 'user-4',
    stravaActivityId: '1014',
    title: 'Chạy 8km thứ 5 bận cuối tuần',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2880,
    elapsedTimeSec: 2950,
    averagePaceSeconds: 360,
    elevationGain: 12,
    startDate: '2026-10-15T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-5: Hoàng Lan Anh - Chạy 3 buổi nhưng tổng 14.5km (Thiếu 0.5km -> Làm tròn 1km -> Phạt 20k & nợ 0.5km)
  {
    id: 'act-501',
    userId: 'user-5',
    stravaActivityId: '1015',
    title: 'Chạy 5km',
    type: 'Run',
    distanceKm: 5.0,
    movingTimeSec: 2000, // 6:40/km
    elapsedTimeSec: 2050,
    averagePaceSeconds: 400,
    elevationGain: 5,
    startDate: '2026-10-12T18:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-502',
    userId: 'user-5',
    stravaActivityId: '1016',
    title: 'Chạy 5km',
    type: 'Run',
    distanceKm: 5.0,
    movingTimeSec: 2000,
    elapsedTimeSec: 2050,
    averagePaceSeconds: 400,
    elevationGain: 5,
    startDate: '2026-10-14T18:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-503',
    userId: 'user-5',
    stravaActivityId: '1017',
    title: 'Chạy 4.5km mệt nên nghỉ sớm',
    type: 'Run',
    distanceKm: 4.5,
    movingTimeSec: 1800,
    elapsedTimeSec: 1850,
    averagePaceSeconds: 400,
    elevationGain: 5,
    startDate: '2026-10-17T18:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 4.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // -----------------------------------------------------------
  // TEAM 2: Rùa Vàng Bền Bỉ
  // user-6: Đặng Thanh Tùng (Đội trưởng) - Trail run / leo núi (pace 14:30/km) + 2 bài Road
  {
    id: 'act-601',
    userId: 'user-6',
    stravaActivityId: '2001',
    title: 'Trail Run Hàm Lợn Sóc Sơn',
    type: 'TrailRun',
    distanceKm: 12.0,
    movingTimeSec: 10440, // 14:30/km (870s)
    elapsedTimeSec: 11000,
    averagePaceSeconds: 870,
    elevationGain: 480,
    startDate: '2026-10-12T07:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 12.0,
    isTrailOrHike: true,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-602',
    userId: 'user-6',
    stravaActivityId: '2002',
    title: 'Chạy hồi phục sau trail',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2520, // 7:00/km
    elapsedTimeSec: 2600,
    averagePaceSeconds: 420,
    elevationGain: 10,
    startDate: '2026-10-15T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-603',
    userId: 'user-6',
    stravaActivityId: '2003',
    title: 'Chạy cuối tuần',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 3360, // 7:00/km
    elapsedTimeSec: 3450,
    averagePaceSeconds: 420,
    elevationGain: 15,
    startDate: '2026-10-18T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-7: Vũ Quốc Huy - 3 buổi, tổng 25km (pace 7:15/km - chiến thuật pace chậm tranh giải Tie-breaker!)
  {
    id: 'act-701',
    userId: 'user-7',
    stravaActivityId: '2004',
    title: 'Rùa vàng cày dặm 8km',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 3480, // 7:15/km (435s)
    elapsedTimeSec: 3550,
    averagePaceSeconds: 435,
    elevationGain: 10,
    startDate: '2026-10-13T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-702',
    userId: 'user-7',
    stravaActivityId: '2005',
    title: 'Rùa vàng cày dặm 8km',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 3480,
    elapsedTimeSec: 3550,
    averagePaceSeconds: 435,
    elevationGain: 10,
    startDate: '2026-10-15T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-703',
    userId: 'user-7',
    stravaActivityId: '2006',
    title: 'Long run rùa vàng 9km',
    type: 'Run',
    distanceKm: 9.0,
    movingTimeSec: 3915,
    elapsedTimeSec: 4000,
    averagePaceSeconds: 435,
    elevationGain: 15,
    startDate: '2026-10-18T05:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 9.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-8: Nguyễn Mai Chi (Nữ) - Trekking Ba Vì + 2 buổi chạy
  {
    id: 'act-801',
    userId: 'user-8',
    stravaActivityId: '2007',
    title: 'Trekking Vườn Quốc Gia Ba Vì',
    type: 'Hike',
    distanceKm: 10.0,
    movingTimeSec: 9600, // 16:00/km (960s)
    elapsedTimeSec: 11000,
    averagePaceSeconds: 960,
    elevationGain: 550,
    startDate: '2026-10-14T08:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 10.0,
    isTrailOrHike: true,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-802',
    userId: 'user-8',
    stravaActivityId: '2008',
    title: 'Chạy nhẹ chiều thứ sáu',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2310, // 7:00/km
    elapsedTimeSec: 2400,
    averagePaceSeconds: 420,
    elevationGain: 8,
    startDate: '2026-10-16T17:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-803',
    userId: 'user-8',
    stravaActivityId: '2009',
    title: 'Chạy chủ nhật',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2520,
    elapsedTimeSec: 2600,
    averagePaceSeconds: 420,
    elevationGain: 10,
    startDate: '2026-10-18T06:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-9: Bùi Tuấn Anh - 3 buổi, tổng 21km
  {
    id: 'act-901',
    userId: 'user-9',
    stravaActivityId: '2010',
    title: 'Chạy sáng thứ 3',
    type: 'Run',
    distanceKm: 7.0,
    movingTimeSec: 2940, // 7:00/km
    elapsedTimeSec: 3000,
    averagePaceSeconds: 420,
    elevationGain: 12,
    startDate: '2026-10-13T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 7.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-902',
    userId: 'user-9',
    stravaActivityId: '2011',
    title: 'Chạy sáng thứ 5',
    type: 'Run',
    distanceKm: 7.0,
    movingTimeSec: 2940,
    elapsedTimeSec: 3000,
    averagePaceSeconds: 420,
    elevationGain: 12,
    startDate: '2026-10-15T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 7.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-903',
    userId: 'user-9',
    stravaActivityId: '2012',
    title: 'Chạy sáng chủ nhật',
    type: 'Run',
    distanceKm: 7.0,
    movingTimeSec: 2940,
    elapsedTimeSec: 3000,
    averagePaceSeconds: 420,
    elevationGain: 12,
    startDate: '2026-10-18T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 7.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-10: Đỗ Hồng Nhung (Nữ) - 3 buổi, tổng 16.5km
  {
    id: 'act-1001',
    userId: 'user-10',
    stravaActivityId: '2013',
    title: 'Chạy 5.5km',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2365, // 7:10/km (430s)
    elapsedTimeSec: 2450,
    averagePaceSeconds: 430,
    elevationGain: 8,
    startDate: '2026-10-12T17:45:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1002',
    userId: 'user-10',
    stravaActivityId: '2014',
    title: 'Chạy 5.5km',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2365,
    elapsedTimeSec: 2450,
    averagePaceSeconds: 430,
    elevationGain: 8,
    startDate: '2026-10-14T17:45:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1003',
    userId: 'user-10',
    stravaActivityId: '2015',
    title: 'Chạy 5.5km',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2365,
    elapsedTimeSec: 2450,
    averagePaceSeconds: 430,
    elevationGain: 8,
    startDate: '2026-10-16T17:45:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // -----------------------------------------------------------
  // TEAM 3: Thần Tốc Bắc Hà
  // user-11: Phan Minh Trí (Đội trưởng) - Chạy 3 buổi, tổng 24km (pace 4:45/km)
  {
    id: 'act-1101',
    userId: 'user-11',
    stravaActivityId: '3001',
    title: 'Tăng tốc đầu tuần',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2280, // 4:45/km (285s)
    elapsedTimeSec: 2350,
    averagePaceSeconds: 285,
    elevationGain: 15,
    startDate: '2026-10-13T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1102',
    userId: 'user-11',
    stravaActivityId: '3002',
    title: 'Chạy biến tốc',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2280,
    elapsedTimeSec: 2350,
    averagePaceSeconds: 285,
    elevationGain: 15,
    startDate: '2026-10-15T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1103',
    userId: 'user-11',
    stravaActivityId: '3003',
    title: 'Chạy dài tốc độ',
    type: 'Run',
    distanceKm: 8.0,
    movingTimeSec: 2280,
    elapsedTimeSec: 2350,
    averagePaceSeconds: 285,
    elevationGain: 15,
    startDate: '2026-10-18T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 8.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-12: Trịnh Bảo Ngọc (Nữ) - 3 buổi 17km
  {
    id: 'act-1201',
    userId: 'user-12',
    stravaActivityId: '3004',
    title: 'Morning workout',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2160, // 6:00/km
    elapsedTimeSec: 2200,
    averagePaceSeconds: 360,
    elevationGain: 10,
    startDate: '2026-10-12T06:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1202',
    userId: 'user-12',
    stravaActivityId: '3005',
    title: 'Midweek run',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 1980,
    elapsedTimeSec: 2050,
    averagePaceSeconds: 360,
    elevationGain: 8,
    startDate: '2026-10-14T06:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1203',
    userId: 'user-12',
    stravaActivityId: '3006',
    title: 'Sunday long run',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 1980,
    elapsedTimeSec: 2050,
    averagePaceSeconds: 360,
    elevationGain: 8,
    startDate: '2026-10-18T06:30:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-13: Lý Quốc Bảo - 3 buổi 18km (có 1 bài bị lag trừ 1km)
  {
    id: 'act-1301',
    userId: 'user-13',
    stravaActivityId: '3007',
    title: 'Chạy GPS lag bị trừ 1km',
    type: 'Run',
    distanceKm: 7.0,
    movingTimeSec: 2450, // 5:50/km (350s)
    elapsedTimeSec: 2500,
    averagePaceSeconds: 350,
    elevationGain: 10,
    startDate: '2026-10-13T06:00:00Z',
    lagKmDeducted: 1.0, // GPS nhảy lố 1km, BTC trừ còn 6km
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1302',
    userId: 'user-13',
    stravaActivityId: '3008',
    title: 'Chạy thứ 5',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2100,
    elapsedTimeSec: 2150,
    averagePaceSeconds: 350,
    elevationGain: 10,
    startDate: '2026-10-15T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1303',
    userId: 'user-13',
    stravaActivityId: '3009',
    title: 'Chạy chủ nhật',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2100,
    elapsedTimeSec: 2150,
    averagePaceSeconds: 350,
    elevationGain: 10,
    startDate: '2026-10-18T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-14: Dương Thị Tuyết (Nữ) - 3 buổi 16km
  {
    id: 'act-1401',
    userId: 'user-14',
    stravaActivityId: '3010',
    title: 'Sáng thứ 2 khởi động',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2145, // 6:30/km
    elapsedTimeSec: 2200,
    averagePaceSeconds: 390,
    elevationGain: 5,
    startDate: '2026-10-12T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1402',
    userId: 'user-14',
    stravaActivityId: '3011',
    title: 'Sáng thứ 4',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 2145,
    elapsedTimeSec: 2200,
    averagePaceSeconds: 390,
    elevationGain: 5,
    startDate: '2026-10-14T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1403',
    userId: 'user-14',
    stravaActivityId: '3012',
    title: 'Sáng thứ 6',
    type: 'Run',
    distanceKm: 5.0,
    movingTimeSec: 1950,
    elapsedTimeSec: 2000,
    averagePaceSeconds: 390,
    elevationGain: 5,
    startDate: '2026-10-16T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // user-15: Cao Văn Hùng - Có 1 bài chạy < 1km bị loại (0.8km) + 3 bài hợp lệ
  {
    id: 'act-1500',
    userId: 'user-15',
    stravaActivityId: '3013',
    title: 'Chạy nhầm tắt đồng hồ sớm (0.8km)',
    type: 'Run',
    distanceKm: 0.8,
    movingTimeSec: 280,
    elapsedTimeSec: 300,
    averagePaceSeconds: 350,
    elevationGain: 0,
    startDate: '2026-10-12T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 0.8,
    isTrailOrHike: false,
    isValid: false,
    invalidReasons: ['Cự ly dưới 1.0 km'],
  },
  {
    id: 'act-1501',
    userId: 'user-15',
    stravaActivityId: '3014',
    title: 'Bật lại chạy đủ 6km',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2100,
    elapsedTimeSec: 2150,
    averagePaceSeconds: 350,
    elevationGain: 5,
    startDate: '2026-10-12T06:15:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1502',
    userId: 'user-15',
    stravaActivityId: '3015',
    title: 'Chạy thứ 4',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 1925,
    elapsedTimeSec: 1980,
    averagePaceSeconds: 350,
    elevationGain: 5,
    startDate: '2026-10-14T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-1503',
    userId: 'user-15',
    stravaActivityId: '3016',
    title: 'Chạy thứ 6',
    type: 'Run',
    distanceKm: 5.5,
    movingTimeSec: 1925,
    elapsedTimeSec: 1980,
    averagePaceSeconds: 350,
    elevationGain: 5,
    startDate: '2026-10-16T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 5.5,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },

  // -----------------------------------------------------------
  // TUẦN 2 (19/10/2026 - 25/10/2026):
  // Minh họa thành viên user-5 (Hoàng Lan Anh) tuần 1 nợ 0.5km -> Tuần 2 chỉ tiêu thành 15.5km
  // Tuần 2 chị chạy 3 buổi 6km = 18km -> Trả hết nợ và hoàn thành xuất sắc!
  {
    id: 'act-w2-501',
    userId: 'user-5',
    stravaActivityId: '4001',
    title: 'Tuần 2: Chạy trả nợ buổi 1',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2400,
    elapsedTimeSec: 2450,
    averagePaceSeconds: 400,
    elevationGain: 10,
    startDate: '2026-10-19T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-w2-502',
    userId: 'user-5',
    stravaActivityId: '4002',
    title: 'Tuần 2: Chạy trả nợ buổi 2',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2400,
    elapsedTimeSec: 2450,
    averagePaceSeconds: 400,
    elevationGain: 10,
    startDate: '2026-10-21T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
  {
    id: 'act-w2-503',
    userId: 'user-5',
    stravaActivityId: '4003',
    title: 'Tuần 2: Vượt chỉ tiêu 18km',
    type: 'Run',
    distanceKm: 6.0,
    movingTimeSec: 2400,
    elapsedTimeSec: 2450,
    averagePaceSeconds: 400,
    elevationGain: 10,
    startDate: '2026-10-23T06:00:00Z',
    lagKmDeducted: 0,
    effectiveKm: 6.0,
    isTrailOrHike: false,
    isValid: true,
    invalidReasons: [],
  },
];

// Validate all sample activities
const validatedActivities = sampleActivities.map((act) => {
  const res = validateActivity(act);
  return {
    ...act,
    isValid: res.isValid,
    invalidReasons: res.invalidReasons,
  };
});

baseData.activities = validatedActivities;
saveData(baseData);

console.log(`✅ Đã nạp thành công:`);
console.log(`   - 8 Tuần giải`);
console.log(`   - 3 Đội thi đấu`);
console.log(`   - ${baseData.users.length} Vận động viên (Nam & Nữ)`);
console.log(`   - ${validatedActivities.length} Bài chạy mẫu (Road, Trail Run, Trekking)`);
